"""empty message

Revision ID: 1eae9952030d
Revises: 8dacd0a61fa7
Create Date: 2022-03-12 11:58:48.025297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eae9952030d'
down_revision = '8dacd0a61fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_model', sa.String(length=300), nullable=False),
    sa.Column('item_serial', sa.String(length=300), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('item_image', sa.String(length=300), nullable=True),
    sa.Column('item_checkout_date', sa.DateTime(), nullable=False),
    sa.Column('item_date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
